CREATE DATABASE IF NOT EXISTS MEDICARE_DB;
USE DATABASE MEDICARE_DB;

CREATE OR REPLACE TABLE RAW_PRESCRIBER_DATA (
    PRSCRBR_NPI INTEGER,
    PRSCRBR_LAST_ORG_NAME STRING,
    PRSCRBR_FIRST_NAME STRING,
    PRSCRBR_CITY STRING,
    PRSCRBR_STATE_ABBR STRING,
    PRSCRBR_TYPE STRING,        
    BRND_NAME STRING,          
    TOT_CLMS INTEGER,         
    TOT_DAY_SUPLY INTEGER,      
    TOT_DRUG_CST FLOAT);
